### PR TITLE
Various fixes

### LINKED ISSUE #37: Validation with supported languages
When creating a function, the cli should do some validation to check if the code is supported. For now we could just check the extension of the file user. The current supported language is javascript, so we should accept only files ending in .js.

### LINKED ISSUE #83: Function/module name validation
We should do a simple check that a function doesnt have weird characters.

Use the same regex as in the core, so we avoid queries and we can give better feedback when a name won't work.

### LINKED ISSUE #94: Check exit status from builder to be sure it didnt crash
If you pass the wrong --language flag (e.g. js for rust code) the builder will crash and the cli might think it finished successfully.

### PR DESCRIPTION
**Pull request by mattrent**
This PR fixes various previously unhandled issues. Specifically:
- It closes #37, adding a validation step in `build` and `create`, searching for necessary files in the given source directory, for the given language
- It closes #83, adding a validation step in `FnService` and `ModService` functions, checking the function and module names match the same regex used in the core
- It closes #94, checking the exit status code of containers in the `RunAndWait` function of `DockerClient`

### CODE REVIEW

File: pkg/client/fn_service_test.go [hunk 1]
```diff
@@ -27,15 +27,19 @@ import (
...
 
 func TestFnInvoke(t *testing.T) {
-	testFn := "test-fn"
-	testNs := "test-ns"
+	testFn := "test_fn"
+	testNs := "test_ns"
 	var testArgs map[string]interface{} = map[string]interface{}{"name": "Some name"}
 
 	testCtx := context.Background()
+	mockValidator := mocks.NewInputValidatorHandler(t)
```
Comment (giusdp) [inline pkg/client/fn_service_test.go:40]: Do we really need to mock the validator? It doesn't have any interaction with external systems. We can just use the concrete type and do the real validation.

Comment (mattrent) [reply pkg/client/fn_service_test.go:40]: It was mostly done to use the `AssertNumberOfCalls` in tests, to ensure fn/mod functions call the input validation, while testing the actual validation in a separate file. Without the mock we would have to check the validation in each fn/mod function call I think

Comment (giusdp) [reply pkg/client/fn_service_test.go:40]: Perhaps we could use the concrete type and have a test in mod/fn_service where we try to create a function with an invalid name and check that it returns an error and the request doesn't go through, so we avoid mocking and we check that the validator actually stops the request.

If you want to give it a try and see how the tests look like it'd be great. Afterwards we can either integrate that or just merge how it is now.

Comment (mattrent) [reply pkg/client/fn_service_test.go:40]: After trying the test design using the concrete validator instead of the mock, I found that (to have a complete coverage), new tests should be added for all `fn` and `mod` subcommands. This would result in simply replicating the validator tests, instead of isolating them in one file. 
I think we can keep the tests as they are right now, and if the validator is changed or expanded in the future, simply update its tests; if, instead, we find that the validator is better suited as a simple auxiliary function, we can scrap the whole interface/struct and integrate the relative tests in the subcommands.

**Review by giusdp — APPROVED** [review]
